[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"

# The title and description fields are primarily for displaying extension info in UI
title = "LightCube Generator Tool"
description="Generate a matrix of lightcubes with different color patterns on the push of a button"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "README.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Scene Generator"

# Keywords for the extension
keywords = ["kit", "lightcube_generator", "lightbox", "cube pattern"]


# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}

# Main python module this extension provides, it will be publicly available as "import light_box.cube.test".
[[python.module]]
name = "light_box.cube.v1"